# coding: UTF-8

flag_wip         = ::RuuubyFeature::EnumFlagState::STATE_WIP
flag_needs_merge = ::RuuubyFeature::EnumFlagState::STATE_NEEDS_MERGE
flag_todo        = ::RuuubyFeature::EnumFlagState::STATE_NULL
flag_stable      = ::RuuubyFeature::EnumFlagState::STATE_STABLE

@f00 = RuuubyFeature.spawn(0, "`η̂` to alias concept of `normalization` (offered in any applicable context)", flag_wip, %w())
@f01 = RuuubyFeature.spawn(1, 'simplify debugging state & logging through the `RuuubyEngine`', flag_wip, %w())
@f02 = RuuubyFeature.spawn(2, 'augment working with other `API` sets, be it a small `CLI script` to larger `domain-driven/micro-services` representations', flag_wip, %w(ruuuby engine cli))
@f03 = RuuubyFeature.spawn(3, "`𝔠` to alias concept of `cardinality`", flag_wip, %w())
@f04 = RuuubyFeature.spawn(4, '`∅` to alias concept of `empty`', flag_wip, %w())
@f05 = RuuubyFeature.spawn(5, '`>>` to offer reverse functionality of `<<`', flag_wip, %w(str ary))
@f06 = RuuubyFeature.spawn(6, 'enable quick type checks against any object (ex: `variable.int?`)', flag_needs_merge, %w())
@f07 = RuuubyFeature.spawn(7, 'enable quick clean up functions for `enumerables`', flag_needs_merge, %w())
@f08 = RuuubyFeature.spawn(8, 'enable quick editing functions for `enumerables` (& `String`)', flag_needs_merge, %w())
@f09 = RuuubyFeature.spawn(9, 'add math `notation & operations` for both `set`(ex: `Set`) and `multiset`(ex: `Array`)', flag_needs_merge, %w(math set multiset enumerables set-theory))
@f10 = RuuubyFeature.spawn(10, 'offer special character aliases for natural ease of readability', flag_wip, %w())
@f11 = RuuubyFeature.spawn(11, 'abstract `SetTheory` and offer discrete singleton objs which reference various groups of numbers', flag_wip, %w(math set-theory))
@f12 = RuuubyFeature.spawn(12, 'enable more simple `file/directory io`', flag_wip, %w())
@f13 = RuuubyFeature.spawn(13, '`∃` to alias concept of `does this(arg) exist?` and `∄` to mean inverse: `does this(arg) not exist?`', flag_wip, %w())
@f14 = RuuubyFeature.spawn(14, 'enable easier catching and throwing of parameter type errors', flag_wip, %w())
@f15 = RuuubyFeature.spawn(15, 'enable quicker tracking and auditing of features across versions', flag_wip, %w())
@f16 = RuuubyFeature.spawn(16, 'for specific classes, patch in the operation of raising to an exponent, using operator(`^`) w/ `superscripts`', flag_wip, %w())
@f17 = RuuubyFeature.spawn(17, 'abstract `Trigonometry`; offering static math functions', flag_wip, %w(math trigonometry trig))
@f18 = RuuubyFeature.spawn(18, 'represent needed fields of math into organized groupings w/ abstractions', flag_wip, %w(math))
@f19 = RuuubyFeature.spawn(19, 'add support for automatic-differentiation', flag_todo, %w(math automatic-differentiation AD auto-diff))
@f20 = RuuubyFeature.spawn(20, 'enable easier (general) syntax & pattern parsing', flag_needs_merge, %w())
@f21 = RuuubyFeature.spawn(21, 'enable easier textual/numerical/syntax parsing', flag_needs_merge, %w())
@f22 = RuuubyFeature.spawn(22, 'add a light abstraction to working w/ the built-in `GC` & `JIT` utilities', flag_wip, %w(ruuuby engine gc jit))
@f23 = RuuubyFeature.spawn(23, "gather statistics (and/or more debugging information) on `Ruuuby` {example-context: optimizing ordering of if-conditions / function-calls}", flag_wip, %w(ruuuby engine))
@f24 = RuuubyFeature.spawn(24, "Class(String): add syntax parsing for snake-case and camel-case", flag_needs_merge, %w())
@f25 = RuuubyFeature.spawn(25, "bundle `Ruuuby` meta-data related functionality w/ base alias(`💎`)", flag_needs_merge, %w())
@f26 = RuuubyFeature.spawn(26, 'enable more simple syntax parsing for `ISO8601` and other time operations', flag_needs_merge, %w())
@f27 = RuuubyFeature.spawn(27, 'add new class (`ThetaAngle`) for easier operations involving angles', flag_wip, %w())
@f28 = RuuubyFeature.spawn(28, 'formally support various math constants & equations (ex: aliasing the golden-ratio w/ (`𝚽`)', flag_wip, %w(math geometry symbolic-math))
@f29 = RuuubyFeature.spawn(29, 'add new class (`Quaternion`) for easier operations involving `quaternions`', flag_todo, %w(math linear-algebra Quaternion))
@f30 = RuuubyFeature.spawn(30, 'mimic `SetTheory` by creating data-type groupings for Ruby data', flag_wip, %w())
@f31 = RuuubyFeature.spawn(31, 'provide a `GIT API`', flag_wip, %w(ruuuby engine git api))
@f32 = RuuubyFeature.spawn(32, 'abstract `NumberTheory`; offering static math functions', flag_wip, %w(math number-theory))
@f33 = RuuubyFeature.spawn(33, 'abstract `Combinatorics`; offering static math functions', flag_wip, %w(math combinatorics))
@f34 = RuuubyFeature.spawn(34, 'abstract `Geometry`; offering static math functions; esp. those for `Shapes`', flag_wip, %w(math geometry))
@f35 = RuuubyFeature.spawn(35, 'abstract `Statistics`; offering static math functions', flag_wip, %w(math statistics stats))


@f95 = RuuubyFeature.spawn(95, 'enable pure a `Ruby` only build', flag_todo, %w(builds))
@f96 = RuuubyFeature.spawn(96, 'painlessly support multiple Operation Systems (ex: Alpine Linux, macOS, etc)', flag_todo, %w(OS docker kubernetes))
@f97 = RuuubyFeature.spawn(97, 'offer custom builds of `Ruuuby` to support only the needed/wanted unicode/symbols/emojis etc', flag_wip, %w(builds))
@f98 = RuuubyFeature.spawn(98, '`C-extensions`', flag_wip, %w(builds extensions))
@f99 = RuuubyFeature.spawn(99, '`Java-extensions`/`JRuby`', flag_wip, %w(builds extensions))
