# @see https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

#  __                  __          __   __   ___  ___  ___  __   ___       __   ___  __
# |__) |  | |  | |  | |__) \ /    |__) |__) |__  |__  |__  |__) |__  |\ | /  ` |__  /__`
# |  \ \__/ \__/ \__/ |__)  |     |    |  \ |___ |    |___ |  \ |___ | \| \__, |___ .__/

Naming/AsciiIdentifiers:
  Enabled: False

Style/AsciiComments:
  Enabled: False

Style/FrozenStringLiteralComment:
  Enabled: False

Layout/SpaceAroundOperators:
  Enabled: False

Layout/ExtraSpacing:
  Enabled: False

Style/ClassAndModuleChildren:
  Enabled: False

Style/SingleLineMethods:
  Enabled: False

Naming/VariableName:
  Enabled: False

#  __   ___  ___                ___  __
# |  \ |__  |__   /\  |  | |     |  /__`
# |__/ |___ |    /~~\ \__/ |___  |  .__/

Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true

Lint/EmptyBlock: # (new in 1.1)
  Enabled: true

Lint/EmptyClass: # (new in 1.3)
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true

Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true

Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true

Style/CollectionCompact: # (new in 1.2)
  Enabled: true

Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true

Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true

Style/NilLambda: # (new in 1.3)
  Enabled: true

Style/RedundantArgument: # (new in 1.4)
  Enabled: true

Style/SwapValues: # (new in 1.1)
  Enabled: true
