# {'Compose file format': '3.8', 'Docker Engine release': '19.03.13'}; utilized API-Version: `1.40`
version: '3.8'

services:

  # TODO: ruuuby server

  service_nginx:
    build:
      context: ./services/nginx
      dockerfile: ./Dockerfile
      target: build_env_test
    tty: false
    environment:
      SERVICE_ENV: 'test'
    volumes:
      - 'vol_nginx_test:/v'
    ports:
      - 1337:1337
      - 8080:8080
      - 15672:15672
      - 80:80
    depends_on:
      - service_postgres
      - service_pgadmin
      - service_js
      - service_rabbitmq

  #image: 'rabbitmq:3-management'
  service_rabbitmq:
    build:
      context: ./services/rabbitmq
      dockerfile: ./Dockerfile
      #target: build_env_test
    environment:
      RABBIT_ERLANG_COOKIE: 'secret string'
      RABBIT_NODENAME: 'service_rabbitmq'
    ports:
      - 5672:5672
    volumes:
      - 'vol_rabbitmq_test:/data'
      - './services/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config'
      - './services/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json'

  service_js:
    build:
      context: ./services/web_assets
      dockerfile: ./Dockerfile
      target: build_env_test
    tty: false
    environment:
      SERVICE_ENV: 'test'
      SERVICE_PORT: '8080'
      SERVICE_HOST: 'http://localhost'

  service_postgres:
    image: 'amd64/postgres:13-alpine'
    command: postgres -c 'max_connections=10'
    restart: always
    tty: false
    environment:
      SERVICE_NAME: 'service_postgres'
      BUILD_ENV: 'test'
      SERVICE_ENV: 'test'
      SERVICE_OS: 'alpine'
      SERVICE_OS_VERSION: '3.12.0'
      POSTGRES_DB: 'env_test'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypassword'
    ports:
      - 5432:5432
    volumes:
      - 'vol_db_test/:/var/lib/postgresql/data/'

  service_pgadmin:
    image: 'dpage/pgadmin4'
    tty: false
    environment:
      SERVICE_NAME: 'service_pgadmin'
      BUILD_ENV: 'test'
      SERVICE_ENV: 'test'
      SERVICE_OS: 'alpine'
      SERVICE_OS_VERSION: '3.9.4'
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_ADMIN_PORT: '1337'
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
    volumes:
      - 'vol_pgadmin_test/:/var/lib/pgadmin/'

networks:
  default:
    external:
      name: ruuuby_network

volumes:
  vol_db_test:
    external: true
  vol_nginx_test:
    external: true
  vol_pgadmin_test:
    external: true
  vol_rabbitmq_test:
    external: true
