# {'Compose file format': '3.8', 'Docker Engine release': '19.03.13'}; utilized API-Version: `1.40`
version: '3.8'

services:

  # TODO: ruuuby server

  service_nginx_dev:
    container_name: "service_nginx_dev"
    build:
      context: ./services/nginx
      dockerfile: ./Dockerfile
      target: build_env_dev
    tty: false
    environment:
      SERVICE_ENV: 'dev'
    volumes:
      - 'vol_nginx_dev:/v'
    ports:
      - 1337:1337
      - 8080:8080
      - 15672:15672
      - 13337:13337
    depends_on:
      - service_postgresql_dev
      - service_pgadmin_dev
      - service_js_dev
      - service_rabbitmq_dev

  service_rabbitmq_dev:
    container_name: "service_rabbitmq_dev"
    build:
      context: ./services/rabbitmq
      dockerfile: ./Dockerfile
    environment:
      RABBIT_ERLANG_COOKIE: 'secret string'
      RABBIT_NODENAME: 'service_rabbitmq'
    ports:
      - 5672:5672
    volumes:
      - 'vol_rabbitmq_dev:/data'
      - './services/rabbitmq/dev/rabbitmq.config:/etc/rabbitmq/rabbitmq.config'
      - './services/rabbitmq/dev/definitions.json:/etc/rabbitmq/definitions.json'

  service_js_dev:
    container_name: "service_js_dev"
    build:
      context: ./services/web_assets
      dockerfile: ./Dockerfile
      target: build_env_dev
    tty: false
    environment:
      SERVICE_ENV: 'dev'
      SERVICE_PORT: '8080'
      SERVICE_HOST: 'http://localhost'

  service_postgresql_dev:
    container_name: "service_postgresql_dev"
    build:
      context: ./services/ruuuby_db
      dockerfile: ./Dockerfile
    command: postgres -c 'max_connections=10'
    restart: always
    tty: false
    environment:
      SERVICE_ENV: 'dev'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypassword'
      POSTGRES_DB: 'env_dev'
    ports:
      - 5432:5432
    volumes:
      - 'vol_db_dev/:/var/lib/postgresql/data/'
      - './services/ruuuby_db/init.sql:/docker-entrypoint-initdb.d/init.sql'

  service_pgadmin_dev:
    container_name: "service_pgadmin_dev"
    build:
      context: ./services/pgadmin
      dockerfile: ./Dockerfile
    tty: false
    environment:
      BUILD_ENV: 'dev'
      SERVICE_ENV: 'dev'
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_ADMIN_PORT: '13337'
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
      PGADMIN_LISTEN_PORT: '13337'
      GUNICORN_THREADS: '15'
    volumes:
      - 'vol_pgadmin_dev/:/var/lib/pgadmin/'

networks:
  default:
    external:
      name: ruuuby_network

volumes:
  vol_db_dev:
    external: true
  vol_nginx_dev:
    external: true
  vol_pgadmin_dev:
    external: true
  vol_rabbitmq_dev:
    external: true
