version: '3.8'

services:

  service_nginx:
    build:
      context: ./services/nginx
      dockerfile: ./Dockerfile
      target: build_env_prod
    tty: false
    environment:
      SERVICE_ENV: 'prod'
    volumes:
      - 'vol_nginx_prod:/v'
    ports:
      - 1339:1339
      - 8082:8082
      - 15674:15674
      - 13339:13339
    depends_on:
      - service_postgresql
      - service_pgadmin
      - service_js
      - service_rabbitmq

  service_rabbitmq:
    build:
      context: ./services/rabbitmq
      dockerfile: ./Dockerfile
    environment:
      RABBIT_ERLANG_COOKIE: 'secret string'
      RABBIT_NODENAME: 'service_rabbitmq'
    ports:
      - 5674:5674
    volumes:
      - 'vol_rabbitmq_prod:/data'
      - './services/rabbitmq/prod/rabbitmq.config:/etc/rabbitmq/rabbitmq.config'
      - './services/rabbitmq/prod/definitions.json:/etc/rabbitmq/definitions.json'

  service_js:
    build:
      context: ./services/web_assets
      dockerfile: ./Dockerfile
      target: build_env_prod
    tty: false
    environment:
      SERVICE_ENV: 'prod'
      SERVICE_PORT: '8082'
      SERVICE_HOST: 'http://localhost'

  service_postgresql:
    container_name: "service_postgresql"
    build:
      context: ./services/ruuuby_db
      dockerfile: ./Dockerfile
    command: postgres -c 'max_connections=10'
    restart: always
    tty: false
    environment:
      SERVICE_ENV: 'prod'
      POSTGRES_DB: 'env_prod'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypassword'
    volumes:
      - "vol_dv_prod/:/var/lib/postgresql/data/"

  service_pgadmin:
    container_name: "service_pgadmin"
    build:
      context: ./services/pgadmin
      dockerfile: ./Dockerfile
    tty: false
    environment:
      BUILD_ENV: 'prod'
      SERVICE_ENV: 'prod'
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_ADMIN_PORT: '13339'
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
      PGADMIN_LISTEN_PORT: '13339'
      GUNICORN_THREADS: '30'
    volumes:
      - 'vol_pgadmin_prod/:/var/lib/pgadmin/'

networks:
  default:
    external:
      name: ruuuby_network

volumes:
  vol_db_prod:
    external: true
  vol_nginx_prod:
    external: true
  vol_pgadmin_v:
    external: true
  vol_rabbitmq_prod:
    external: true
