# {'Compose file format': '3.7', 'Docker Engine release': '18.06.0*'}
version: '3.7'

services:

  #ruuuby:
  #  build:
  #    context: .
  #    dockerfile: ./Dockerfile
  #  environment:
  #    SERVICE_NAME: "ruuuby"
  #  tty: false
  #  # TODO: don't utilize this setup style
  #  volumes:
  #    - ./:/ruuuby

  #postgres:

#volumes:
