# {'Compose file format': '3.8', 'Docker Engine release': '19.03.0+'}; utilized API-Version: `1.40`
version: '3.8'

services:

  service_nginx:
    build:
      context: ./services/nginx
      dockerfile: ./Dockerfile
      target: build_env_prod
    tty: false
    environment:
      SERVICE_ENV: 'prod'
    volumes:
      - 'ruuuby_nginx_data:/v'
    ports:
      - 80:80
      - 443:443
      - 1337:1337
      - 8080:8080
    depends_on:
      - service_postgres
      - service_pgadmin
      - service_js
      - service_rabbitmq

  service_rabbitmq:
    build:
      context: ./services/rabbitmq
      dockerfile: ./Dockerfile
      #target: build_env_prod
    environment:
      RABBIT_ERLANG_COOKIE: 'secret string'
      RABBIT_NODENAME: 'service_rabbitmq'
    ports:
      - 5672:5672
    volumes:
      - 'ruuuby_rabbitmq_data:/data'
      - './services/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config'
      - './services/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json'

  service_js:
    build:
      context: ./services/web_assets
      dockerfile: ./Dockerfile
      target: build_env_prod

  service_postgres:
    image: 'amd64/postgres:13-alpine'
    restart: always
    tty: false
    environment:
      SERVICE_NAME: 'service_postgres'
      BUILD_ENV: 'prod'
      SERVICE_ENV: 'prod'
      SERVICE_OS: 'alpine'
      SERVICE_OS_VERSION: '3.12.0'
      POSTGRES_DB: 'mydb'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypassword'
    volumes:
      - "ruuuby_db_data/:/var/lib/postgresql/data/"

  service_pgadmin:
    image: 'dpage/pgadmin4'
    tty: false
    environment:
      SERVICE_NAME: 'service_pgadmin'
      BUILD_ENV: 'prod'
      SERVICE_ENV: 'prod'
      SERVICE_OS: 'alpine'
      SERVICE_OS_VERSION: '3.9.4'
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_ADMIN_PORT: '1337'
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
    volumes:
      - 'ruuuby_pgadmin_data/:/var/lib/pgadmin/'

networks:
  default:
    external:
      name: ruuuby_network

volumes:
  ruuuby_db_data:
    external: true
  ruuuby_nginx_data:
    external: true
  ruuuby_pgadmin_data:
    external: true
  ruuuby_rabbitmq_data:
    external: true
