version: '3.8'

services:

  service_nginx_test:
    container_name: "service_nginx_test"
    build:
      context: ./services/nginx
      dockerfile: ./Dockerfile
      target: build_env_test
    tty: false
    environment:
      SERVICE_ENV: 'test'
    volumes:
      - 'vol_nginx_test:/v'
    ports:
      - 1338:1338
      - 8081:8081
      - 15673:15673
      - 13338:13338
    depends_on:
      - service_postgresql_test
      - service_pgadmin_test
      - service_js_test
      - service_rabbitmq_test

  service_rabbitmq_test:
    container_name: "service_rabbitmq_test"
    build:
      context: ./services/rabbitmq
      dockerfile: ./Dockerfile
      #target: build_env_test
    environment:
      RABBIT_ERLANG_COOKIE: 'secret string'
      RABBIT_NODENAME: 'service_rabbitmq'
    ports:
      - 5673:5673
    volumes:
      - 'vol_rabbitmq_test:/data'
      - './services/rabbitmq/test/rabbitmq.config:/etc/rabbitmq/rabbitmq.config'
      - './services/rabbitmq/test/definitions.json:/etc/rabbitmq/definitions.json'

  service_js_test:
    container_name: "service_js_test"
    build:
      context: ./services/web_assets
      dockerfile: ./Dockerfile
      target: build_env_test
    tty: false
    environment:
      SERVICE_ENV: 'test'
      SERVICE_PORT: '8081'
      SERVICE_HOST: 'http://localhost'

  service_postgresql_test:
    container_name: "service_postgresql_test"
    build:
      context: ./services/ruuuby_db
      dockerfile: ./Dockerfile
    command: postgres -c 'max_connections=10'
    restart: always
    tty: false
    environment:
      SERVICE_ENV: 'test'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypassword'
      POSTGRES_DB: 'env_test'
    ports:
      - 5433:5432
    volumes:
      - 'vol_db_test/:/var/lib/postgresql/data/'
      - './services/ruuuby_db/init.sql:/docker-entrypoint-initdb.d/init.sql'

  service_pgadmin_test:
    container_name: "service_pgadmin_test"
    build:
      context: ./services/pgadmin
      dockerfile: ./Dockerfile
    tty: false
    environment:
      BUILD_ENV: 'test'
      SERVICE_ENV: 'test'
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_ADMIN_PORT: '13338'
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
      PGADMIN_LISTEN_PORT: '13338'
      GUNICORN_THREADS: '20'
    volumes:
      - 'vol_pgadmin_test/:/var/lib/pgadmin/'

networks:
  default:
    external:
      name: ruuuby_network

volumes:
  vol_db_test:
    external: true
  vol_nginx_test:
    external: true
  vol_pgadmin_test:
    external: true
  vol_rabbitmq_test:
    external: true
