# encoding: UTF-8

@f01 = ::RuuubyFeature.spawn(1, 'simplify debugging state & logging through the `RuuubyEngine`', 2, %w(ruuuby engine logging logs log))
@f02 = ::RuuubyFeature.spawn(2, 'augment working with other `API` sets, be it a small `CLI script` to larger `domain-driven/micro-services` representations', 2, %w(ruuuby engine cli))
@f05 = ::RuuubyFeature.spawn(5, '`>>` to offer reverse functionality of `<<`', 4, %w(str ary >> <<))
@f06 = ::RuuubyFeature.spawn(6, 'offer easy to use type-check funcs for common/core Classes (ex: `variable.int?`)', 1, %w())
@f07 = ::RuuubyFeature.spawn(7, 'offer layer of functionality to easily describe & check various meta-data on Ruby', 1, %w())
@f08 = ::RuuubyFeature.spawn(8, 'enable quick clean-up, editing, etc functions for `enumerables` (including `String`)', 1, %w())
@f09 = ::RuuubyFeature.spawn(9, 'add math `notation & operations` for both `set`(ex: `Set`) and `multiset`(ex: `Array`)', 1, %w(math set multiset enumerables set-theory))
@f10 = ::RuuubyFeature.spawn(10, 'offer special character aliases for natural ease of readability', 2, %w())
@f11 = ::RuuubyFeature.spawn(11, 'abstract `SetTheory` and offer discrete singleton objs which reference various groups of numbers', 2, %w(math set-theory))
@f12 = ::RuuubyFeature.spawn(12, 'enable more simple `file/directory io`', 2, %w(io file dir))
@f14 = ::RuuubyFeature.spawn(14, 'enable easier catching and throwing of parameter type errors', 2, %w())
@f15 = ::RuuubyFeature.spawn(15, 'enable quicker tracking and auditing of features across versions', 2, %w())
@f16 = ::RuuubyFeature.spawn(16, 'for specific classes, patch in the operation of raising to an exponent, using operator(`^`) w/ `superscripts`', 2, %w())
@f17 = ::RuuubyFeature.spawn(17, 'abstract `Trigonometry`; offering static math functions', 2, %w(math trigonometry trig))
@f18 = ::RuuubyFeature.spawn(18, 'represent needed fields of math into organized groupings w/ abstractions', 2, %w(math))
@f19 = ::RuuubyFeature.spawn(19, 'add support for automatic-differentiation', 0, %w(math automatic-differentiation AD auto-diff))
@f20 = ::RuuubyFeature.spawn(20, 'enable easier (general) syntax & pattern parsing', 1, %w())
@f21 = ::RuuubyFeature.spawn(21, 'enable easier textual/numerical/syntax parsing', 1, %w())
@f22 = ::RuuubyFeature.spawn(22, 'add a light abstraction to working w/ the built-in `GC` & `JIT` utilities', 2, %w(ruuuby engine gc jit))
@f23 = ::RuuubyFeature.spawn(23, "gather statistics (and/or more debugging information) on `Ruuuby` {example-context: optimizing ordering of if-conditions / function-calls}", 2, %w(ruuuby engine))
@f24 = ::RuuubyFeature.spawn(24, "Class(String): add syntax parsing for snake-case and camel-case", 1, %w())
@f25 = ::RuuubyFeature.spawn(25, "bundle `Ruuuby` meta-data related functionality w/ base alias(`💎`)", 1, %w())
@f26 = ::RuuubyFeature.spawn(26, 'enable more simple syntax parsing for `ISO8601` and other time operations', 1, %w())
@f27 = ::RuuubyFeature.spawn(27, 'add new class (`ThetaAngle`) for easier operations involving angles', 2, %w())
@f28 = ::RuuubyFeature.spawn(28, 'formally support various math constants & equations (ex: aliasing the golden-ratio w/ (`𝚽`)', 2, %w(math geometry symbolic-math))

@f30 = ::RuuubyFeature.spawn(30, 'mimic `SetTheory` by creating data-type groupings for Ruby data', 2, %w())
@f31 = ::RuuubyFeature.spawn(31, 'provide an `API` for `GIT` operations w/ a light layer over gem{`rugged`}', 2, %w(ruuuby engine git api))
@f32 = ::RuuubyFeature.spawn(32, 'abstract `NumberTheory`; offering static math functions', 2, %w(math number-theory))
@f33 = ::RuuubyFeature.spawn(33, 'abstract `Combinatorics`; offering static math functions', 2, %w(math combinatorics))

@f36 = ::RuuubyFeature.spawn(36, 'add new class (`TimeSeriesData`) for easier operations involving multi-sample based stats', 2, %w(math stats time-series data))
@f37 = ::RuuubyFeature.spawn(37, 'abstract `GraphTheory`; offering static math functions and custom `Graph classes`', 2, %w(math graph-theory graphs))
@f38 = ::RuuubyFeature.spawn(38, 'abstract `Tropical Algebra`; offering static math functions and `Refinements` for specific classes', 2, %w(math tropical-algebra tropical algebra))
@f39 = ::RuuubyFeature.spawn(39, "offer a light wrapper over `Ruby's` default web-based-protocol requests", 2, %w(web http socket https websocket))
