FROM amd64/postgres:13-alpine

ENV SERVICE_NAME=service_postgresql
ENV SERVICE_OS=alpine
ENV BUILD_ENV=env_dev
ENV SERVICE_OS_VERSION='3.12.1'

#WORKDIR /docker-entrypoint-initdb.d
#ADD init.sql /docker-entrypoint-initdb.d/
#EXPOSE 5432
