FROM registry:2

# dpkg --print-architecture
# musl-linux-amd64

# cat /proc/version
# Linux version 5.4.39-linuxkit (root@buildkitsandbox) (gcc version 9.2.0 (Alpine 9.2.0)) #1 SMP Fri May 8 23:03:06 UTC 2020
